Traceback (most recent call last):
  File "/home/hsyang/workspace/20210715_cluster_gan/20210719_cluster_gan.py", line 377, in <module>
    main(args)
  File "/home/hsyang/workspace/20210715_cluster_gan/20210719_cluster_gan.py", line 294, in main
    loss_cd_real = criterion_bce(cd_predict_real_assign, label_one)
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 613, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/torch/nn/functional.py", line 2753, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([100, 1])) is deprecated. Please ensure they have the same size.